name: Testnet check

on:
  push:
    branches:
      - testnet-check
      - testnet-check-phu
  pull_request:
    branches:
      - testnet-check
      - testnet-check-phu

jobs:
  run-testnet-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Docker compose
        run: docker-compose up -d
      - name: check address balances
        run: bash homework/check-balances.sh
      - name: check chain id
        run: bash homework/check-chain-id.sh